# hermes_lite/docker-compose.yml
version: '3.8'

services:
  web:
    build: ./web_api
    container_name: hermes_web
    ports:
      - "5000:5000"
    volumes:
      - ./web_api:/app
      - web_data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - JWT_SECRET_KEY=your_jwt_secret_key
      - SSH_USERNAME=demo_user
      - SSH_PASSWORD=demo_password
      - DATABASE_URL=sqlite:///data/hermes_lite.db
    networks:
      - hermes_network
      - target_network
    depends_on:
      - target_host_alpha
      - target_host_beta

  target_host_alpha:
    build: ./target_host_alpha
    container_name: hermes_alpha
    hostname: alpha
    networks:
      - target_network
    ports:
      - "2222:22"  # Expose SSH port with a different host port

  target_host_beta:
    build: ./target_host_beta
    container_name: hermes_beta
    hostname: beta
    networks:
      - target_network
    ports:
      - "2223:22"  # Expose SSH port with a different host port

volumes:
  web_data:
    driver: local

networks:
  hermes_network:
    driver: bridge
  target_network:
    driver: bridge
